# Generated by Django 5.1.4 on 2024-12-28 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('team', models.TextField()),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(default=True)),
                ('submission_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(db_index=True, max_length=250)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=250)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, max_length=350, null=True)),
                ('status', models.BooleanField(default=True)),
                ('submission_url', models.URLField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, max_length=350, null=True)),
                ('status', models.BooleanField(default=False)),
                ('submission_url', models.URLField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(default=False)),
                ('submission_url', models.URLField()),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctestimonials', to='page.campaigns')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stestimonials', to='page.socials')),
            ],
            options={
                'verbose_name': 'Testimonials',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='landing_page/')),
                ('hero_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(default=True)),
                ('about_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alanding_pages', to='page.aboutus')),
                ('contact_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clanding_pages', to='page.contactform')),
                ('featured_campaigns', models.ManyToManyField(blank=True, related_name='cfeatured_on_landing', to='page.campaigns')),
                ('socials_links', models.ManyToManyField(blank=True, related_name='sfeatured_on_landing', to='page.socials')),
                ('testimonials', models.ManyToManyField(blank=True, related_name='tfeatured_on_landing', to='page.testimonials')),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
            },
        ),
    ]
