# Generated by Django 5.1.4 on 2025-01-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='submission_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
