# Generated by Django 5.1.4 on 2024-12-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactform',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socials',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
